### ISSUE TITLE
Open source smart contract: trustless?

### ISSUE THREAD

**Issue by alfredonodo** [tonwhales/ton-nominators#2]
Hi,
TON nominators are the most important feature for the TON blockchain in order to achieve true decentralisation. Blockchain technology is revolutionary as it removes trust from a third party. So having a partially closed source smart contract requires trust in an intermediary and contradicts the essence of the blockchain. What are the reasons for this?
Thank you

**Comment by ex3ndr** [comment]
Our smart contract is fully open source. Recently we even added verification to our blockchain explorer and you can check that sources are the same. Next you can always compile them and compare with the on in the chain.

**Comment by alfredonodo** [comment]
> Our smart contract is fully open source. Recently we even added verification to our blockchain explorer and you can check that sources are the same. Next you can always compile them and compare with the on in the chain.

Well, so please update the [description page](https://github.com/tonwhales/ton-nominators#testing).

**Comment by ex3ndr** [comment]
Tests are not open, but they are not part of a smart contract.

**Comment by alfredonodo** [comment]
> Tests are not open, but they are not part of a smart contract.

Fine, but in my opinion it is not clear.
